version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "theme/dependencies"
    # Only check for enterprise dependencies.
    allow:
      - dependency-name: "github.com/hashicorp/consul-enterprise"
      - dependency-name: "github.com/google/go-querystring"
      - dependency-name: "github.com/hashicorp/errwrap"
      - dependency-name: "github.com/hashicorp/eventlogger"
      - dependency-name: "github.com/hashicorp/go-licensing"
      - dependency-name: "github.com/hashicorp/nomad-licensing"
      - dependency-name: "github.com/hashicorp/raft-snapshotagent"
      - dependency-name: "github.com/hashicorp/sentinel"
      - dependency-name: "github.com/mattn/go-isatty"
      - dependency-name: "google.golang.org/protobuf"
