---
executor: go
parameters:
  origin_branch:
    type: string
    default: main
  dest_branch:
    type: string
    default: main
steps:
  - run:
      name: prepare initial failing reason
      command: |
        # FAIL_REASON is used in the slack message below.
        # We don't add a custom reason for every case, just the common ones.
        echo "export FAIL_REASON='for an unknown reason, @mahmood please investigate: $CIRCLE_BUILD_URL'" >> $BASH_ENV

  - add_ssh_keys:
      fingerprints:
      # "CircleCI SSH Checkout" SSH key associated with hc-github-team-nomad-core GitHub user
      - "f0:d5:f2:c7:f2:76:3a:50:ec:8e:d4:50:57:c6:04:5d"
  - checkout
  - run: apt-get update; apt-get install -y sudo
  - install-circleci-local-cli
  - run: make deps lint-deps
  - run:
      name: Merge OSS branch
      command: |
        set -eux -o pipefail

        # Configure Git
        git config --global user.email "github-team-nomad-core@hashicorp.com"
        git config --global user.name "hc-github-team-nomad-core"

        origin_branch="<< parameters.origin_branch >>"
        dest_branch="<< parameters.dest_branch >>"
        tmp_branch="ci/oss-merge-${origin_branch}-$(date -u +%Y%m%d%H%M%S)"

        # protect against dest_branch being different from current branch
        git checkout "${dest_branch}"
        git pull

        if ! ./scripts/enterprise/merge-oss.sh "${origin_branch}" "${dest_branch}" "${tmp_branch}"; then
          echo "export FAIL_REASON='because git was unable to auto-merge'" >> $BASH_ENV
          exit 1
        fi

        # quick check and basic compile build
        if ! make check ; then
          echo "export FAIL_REASON='because make check failed after auto-merge'" >> $BASH_ENV
          exit 1
        fi
        if ! make pkg/linux_amd64/nomad ; then
          echo "export FAIL_REASON='because nomad failed to compile after auto-merge'" >> $BASH_ENV
          exit 1
        fi

        # now merge and push
        git checkout ${dest_branch}
        git merge "${tmp_branch}"
        git push origin ${dest_branch}

  - slack/status:
      webhook: $SLACK_WEBHOOK_OSS_ENT_AUTOMERGE
      ## only notify on failing builds to avoid spamming now
      fail_only: true
      failure_message: >
        :red_circle: The Nomad OSS -> ENT merge failed today $FAIL_REASON.
      success_message: >
        :tada: The Nomad OSS -> ENT merge just happened automatically.
