name: Merge CE to ENT Nightly
on:
  schedule:
    - cron: '0 4 * * 1-5'
  workflow_dispatch:
jobs:
  merge-main:
    uses: ./.github/workflows/merge-ce.yaml
    with:
      origin_branch: main
      dest_branch: main
    secrets:
      NOMAD_MERGE_CE_GH_PAT: ${{ secrets.NOMAD_MERGE_CE_GH_PAT }}
      NOMAD_MERGE_CE_SLACK: ${{ secrets.NOMAD_MERGE_CE_SLACK }}

  merge-release-branch:
    strategy:
      # Don't cancel the matrix if one job fails.
      fail-fast: false
      matrix:
        branch:
          - release/1.3.x
          - release/1.2.x
          - release/1.1.x
    uses: ./.github/workflows/merge-ce.yaml
    with:
      origin_branch: ${{ matrix.branch }}
      dest_branch: ${{ matrix.branch }}+ent
    secrets:
      NOMAD_MERGE_CE_GH_PAT: ${{ secrets.NOMAD_MERGE_CE_GH_PAT }}
      NOMAD_MERGE_CE_SLACK: ${{ secrets.NOMAD_MERGE_CE_SLACK }}

  slack-notify-success:
    needs:
      - merge-main
      - merge-release-branch
    runs-on: ubuntu-20.04
    steps:
      - name: Send slack notification on success
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
        with:
          payload: |
            {
              "text": ":green::merge::nomad-happy: Nightly Nomad CE->ENT merge completed *successfully*",
              "attachments": [
                {
                  "color": "#5ABB54",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Workflow:*\n${{ github.workflow }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.NOMAD_MERGE_CE_SLACK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
permissions:
  contents: read