# NOTE FOR FUTURE EDITORS!
# Changes to this file do not need to be backported,
# because on `main` it always pulls over all the previous
# release branches from CE that we support (current-2).

name: Merge CE to ENT Nightly
on:
  schedule:
    - cron: '0 4 * * 1-5'
  workflow_dispatch:
jobs:
  merge-main:
    uses: ./.github/workflows/merge-ce.yaml
    with:
      origin_branch: main
      dest_branch: main

  merge-release-branch:
    strategy:
      # Don't cancel the matrix if one job fails.
      fail-fast: false
      matrix:
        branch:
          - release/1.5.x
          - release/1.4.x
          - release/1.3.x
    uses: ./.github/workflows/merge-ce.yaml
    with:
      origin_branch: ${{ matrix.branch }}
      dest_branch: ${{ matrix.branch }}+ent

  slack-notify-success:
    needs:
      - merge-main
      - merge-release-branch
    runs-on: ['self-hosted', 'linux']
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: ./.github/actions/vault-secrets
        with:
          paths: |-
            kv/data/teams/nomad/slack-webhooks proj-nomad-releases | SLACK_WEBHOOK ;
      - name: Send slack notification on success
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
        with:
          payload: |
            {
              "text": ":green::merge::nomad-happy: Nightly Nomad CE->ENT merge completed *successfully*",
              "attachments": [
                {
                  "color": "#5ABB54",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Workflow:*\n${{ github.workflow }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
permissions:
  contents: write
  id-token: write
